paddle.index_put(Tensor([16, 21],"float64"), tuple(Tensor([16, 21],"bool"),), Tensor([2, 1],"float64"), False, )
paddle.index_put(Tensor([16, 21],"float64"), tuple(Tensor([16, 21],"bool"),), Tensor([2, 1],"float64"), True, )

2025-04-17 03:35:52.558828 test begin: paddle.index_put(Tensor([16, 21],"float64"), tuple(Tensor([16, 21],"bool"),), Tensor([2, 1],"float64"), False, )
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
